export const categories = [
  ["Hotels & Resorts", "#862943"],
  ["MICE & Conference", "#253e72"],
  ["Nature & Eco", "#205336"],
  ["Wellness", "#1b7162"],
  ["Culture & Heritage", "#785025"],
  ["Adventure", "#37651e"],
  ["Food & Beverage", "#923965"],
  ["Boutique & Micro-Stays", "#415e86"],
  ["Leisure & Entertainment", "#50317b"],
  ["Scenic Transport", "#304f76"],
] as const;
const images = [
  "5-Star City Hotel.png",
  "Conference & Business Hotel.png",
  "Forest Edge Resort.png",
  "5-Star Wildlife Lodge.png",
];
// Detail copy can be added here as each opportunity brief is supplied.
export const opportunities = [
  ["5-Star City Hotel", 0, "USD 8–10M"],
  ["Conference & Business Hotel", 1, "~USD 20M"],
  ["Forest Edge Resort", 2, "USD 30–50M"],
  ["5-Star Wildlife Lodge", 0, "~USD 20M"],
  ["Longevity & Wellness Resort", 3, "TBC"],
  ["Heritage & Culture Lodge", 4, "TBC"],
  ["Hotspring Resort", 0, "USD 8–25M+"],
  ["Adventure Theme Park", 5, "USD 5–30M+"],
  ["Heritage Village", 4, "USD 1–4M+"],
  ["Riverfront Promenade", 6, "TBC"],
  ["Capsule Hotel Retreat", 7, "USD 1–3M+"],
  ["Scenic Aerial Adventure Park", 5, "USD 3–10M+"],
  ["Food Hall & Dessert Street", 6, "USD 2–8M+"],
  ["Cinema & Movie Experience", 8, "USD 1–4M+"],
  ["Water Park", 8, "USD 8–25M+"],
  ["Bird Watching Eco-Lodge", 2, "USD 3–7M+"],
  ["Nature Glamping Resort", 2, "USD 2–5M+"],
  ["Cable Car", 9, "USD 10–20M+"],
  ["Wellness Farm Retreat", 3, "USD 3–15M+"],
  ["Alpine Coaster", 5, "USD 3–8M+"],
  ["Mini Golf", 8, "USD 300K – 2M+"],
  ["Children’s Nature Discovery Centre", 8, "USD 1–3M+"],
  ["Eco-Cycle Hub & Scenic Bike Trails", 5, "USD 100K – 750K+"],
  ["Bhutanese Culinary Studio & Chef’s Table", 4, "USD 300K – 1M+"],
  ["River Sports Hub", 5, "USD 250K – 3M+"],
  ["ATV Trail Experience", 5, "USD 300K – 1M+"],
].map(([title, category, investment], index) => ({
  id: index,
  title: String(title),
  category: Number(category),
  investment: String(investment),
  image: `/cards/${images[index % images.length]}`,
  description: "",
}));

export const opportunityDetails = [
  {
    irr: "15–20%",
    timeline: "3–4 years",
    overview:
      "A landmark luxury hotel in GMC's city gateway, designed for high-net-worth travellers, executives and international delegations. Positioned to capture the demand generated by GMC's development activity and growing international visitor profile.",
    highlights: [
      "Prime gateway location within the city core",
      "International brand partnership potential",
      "Corporate and government demand driven by GMC development activity",
    ],
  },
  {
    irr: "12–18%",
    timeline: "4–5 years",
    overview:
      "A purpose-built conference and business hotel serving the growing MICE demand generated by GMC's international business activity, government events and regional conferences.",
    highlights: [
      "Dedicated conference and events facilities",
      "Integrated business hospitality amenities",
      "Strategic position adjacent to GMC's convention infrastructure",
    ],
  },
  {
    irr: "18–25%",
    timeline: "4–6 years",
    overview:
      "A premium nature resort at the edge of GMC's protected forest zone, offering immersive low-density accommodation within one of Asia's most extraordinary biodiversity corridors.",
    highlights: [
      "Low-density, high-value nature tourism model",
      "Adjacent to protected forest and wildlife habitat",
      "Strong alignment with global regenerative travel trends",
    ],
  },
  {
    irr: "20–28%",
    timeline: "3–5 years",
    overview:
      "An ultra-luxury lodge offering exclusive wildlife and nature experiences in one of South Asia's last great wilderness areas. Positioned for the global UHNW experiential travel market.",
    highlights: [
      "Ultra-luxury, all-inclusive revenue model",
      "Exceptional wildlife and nature access",
      "High RevPAR potential in an undersupplied segment",
    ],
  },
];
